version: '3.8'
services:
  moderate:
    build: .
    container_name: moderate-app
    ports:
      - "4100:3100"
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_ISSUER_URL: ${AUTH_ISSUER_URL}
      BASE_URL: ${BASE_URL}
    volumes:
      - types-cache:/data
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  types-cache:

networks:
  shared-network:
    external: true
